// Auto-generated TypeScript declarations for cli
// Source: generate-api-docs.py

export declare class LazyConsole {
}

export declare function RunRegistry(): void;
export declare function ThegentSettings(): void;
export declare function archive_cmd(days: any, domain: any, tier: any): void;
export declare function audit_verify_cmd(format: any): void;
export declare function benchmark_cmd(): void;
export declare function bg_cmd(): string;
export declare function cliproxy_login_cmd(provider: string, force: boolean): void;
export declare function closure_pack_cmd(cd: any): void;
export declare function cockpit_cmd(): void;
export declare function compliance_plugin_check_cmd(plugin_id: string, signature: string): void;
export declare function compliance_redact_cmd(text: string): void;
export declare function compliance_report_cmd(format: any, output: any): void;
export declare function compliance_siem_test_cmd(message: string, severity: string): void;
export declare function concurrency_set_cmd(limit: number): void;
export declare function concurrency_show_cmd(format: any): void;
export declare function config_check_cmd(format: any): void;
export declare function context_history_cmd(query: any, task_id: any, cwd: any, limit: number): void;
export declare function contracts_conformance_cmd(format: any, check_drift: boolean, drift_window: number): void;
export declare function contracts_registry_cmd(format: any): void;
export declare function cost_status_cmd(format: any): void;
export declare function cost_values_cmd(format: any): void;
export declare function dag_add_cmd(task_id: string, agent: string, prompt: string, cd: any, depends_on: any, contract_version: any): void;
export declare function dag_cancel_cmd(task_id: string, cd: any): void;
export declare function dag_checkpoint_cmd(cd: any, reason: string): void;
export declare function dag_checkpoints_cmd(limit: number): void;
export declare function dag_list_cmd(cd: any, format: any): void;
export declare function dag_probe_cmd(cd: any, baseline_id: any): void;
export declare function dag_ready_cmd(cd: any, format: any): void;
export declare function dag_reconcile_cmd(cd: any): void;
export declare function dag_recover_cmd(cd: any, action: string): void;
export declare function dag_remove_cmd(task_id: string, cd: any): void;
export declare function dag_rollback_cmd(checkpoint_id: any, cd: any): void;
export declare function dag_run_cmd(cd: any, dry_run: boolean, task: any, max_parallel: any, lane: any, check_drift: boolean, contract_version: any): void;
export declare function dag_status_cmd(cd: any, format: any): void;
export declare function dag_sync_cmd(cd: any, auto_run_next: boolean): void;
export declare function dag_update_cmd(task_id: string, cd: any, status: any, session_id: any, prompt: any, agent: any, depends_on: any, contract_version: any): void;
export declare function dag_validate_cmd(cd: any): void;
export declare function data_protection_cmd(format: any): void;
export declare function deep_research_cmd(query: string, subreddits: string, output: string): void;
export declare function deferral_list_cmd(): void;
export declare function deferral_resume_cmd(run_id: string): void;
export declare function discovery_parse_cmd(text: string, register: boolean, ppid: number): void;
export declare function discovery_register_cmd(agent: string, pid: number, ppid: number, cwd: string, command: any, args: any, session_id: any, token_usage_json: any, mcp_errors: any): void;
export declare function discovery_scan_cmd(format: any): void;
export declare function dlq_list_cmd(status: any, format: any): void;
export declare function drift_cmd(window: number, format: any, structural_budget: number, semantic_budget: number): void;
export declare function drift_monitor_cmd(prompt: string, agents: Array<string>): void;
export declare function escalate_add_cmd(run_id: string, reason: string, sla_minutes: number, owner: any, lane: string, priority: number): void;
export declare function escalate_approve_cmd(run_id: any): void;
export declare function escalate_list_cmd(past_sla_only: boolean, limit: number, format: any): void;
export declare function escalate_resolve_cmd(run_id: any, resolution: string): void;
export declare function events_cmd(run_id: any, limit: number, format: any): void;
export declare function explain_cmd(run_id: any): void;
export declare function explorer_cmd(): void;
export declare function fallbacks_cmd(run_id: any): void;
export declare function feedback_cmd(run_id: any, score: number, note: any): void;
export declare function forensics_snapshot_cmd(run_id: any, phase: any): void;
export declare function get_exit_message(): void;
export declare function govern_configure_cmd(cd: any, force: boolean): void;
export declare function govern_cost_cmd(owner: any, days: number, format: any): void;
export declare function govern_go_cycle_cmd(cd: any, force: boolean, format: any): void;
export declare function govern_go_health_cmd(cd: any, format: any): void;
export declare function govern_go_status_cmd(cd: any): void;
export declare function govern_go_watch_cmd(cd: any, interval: number, max_cycles: any): void;
export declare function guardrails_check_cmd(prompt: string, agent: any, model: any): void;
export declare function guardrails_show_cmd(): void;
export declare function handoff_cmd(owner: string): void;
export declare function handoff_confirm_cmd(snapshot_id: string, incoming_owner: string, confidence: number): void;
export declare function handoff_list_cmd(limit: number, format: any): void;
export declare function handoff_show_cmd(snapshot_id: string, format: any): void;
export declare function history_cmd(limit: number, format: any): void;
export declare function inbox_list_cmd(owner: any, agent: any, event_type: any, status: any, sources: any, limit: number, format: any): void;
export declare function inbox_wait_cmd(owner: any, agent: any, event_type: any, status: any, sources: any, poll: number, timeout: number, notify: boolean, format: any): void;
export declare function inspect_cmd(session_ids: any, owner: any, tail: number, stderr: boolean, format: any, include_contract: boolean): void;
export declare function interruption_list_cmd(limit: number, format: any): void;
export declare function interruption_snooze_cmd(alert_id: string, minutes: number, itype: string): void;
export declare function list_agents_cmd(): void;
export declare function list_droids_cmd(cd: any): void;
export declare function list_model_contract_schema_cmd(): void;
export declare function list_models_cmd(provider: any, by_model: boolean, refresh: boolean, include_contract: boolean): void;
export declare function load_status_cmd(format: any): void;
export declare function logs_cmd(session_id: any, follow: boolean, stderr: boolean, tail: number, timeout: number, harness: boolean): void;
export declare function loop_cmd(prompt: string, todo_spec: string, agent: any, checker: string, loop_mode: string, cd: any): void;
export declare function loop_send_cmd(session_id: any, prompt: string): void;
export declare function loop_stop_cmd(session_id: any): void;
export declare function metrics_cmd(format: any, no_cache: boolean, limit: number): void;
export declare function migration_cmd(contract_id: string, version: string, format: any): void;
export declare function modes_cmd(format: any, mode: any): void;
export declare function monitor_cmd(interval: number): void;
export declare function observe_summary_cmd(limit: number, drift_window: number, structural_budget: number, semantic_budget: number, format: any, provider: any, trend_samples: number, top_escalations: number): void;
export declare function on_progress(iteration: number, total: number, message: string): void;
export declare function on_worker_output(text: string): void;
export declare function operations_cmd(format: any, operation: any): void;
export declare function pause_cmd(session_id: any): void;
export declare function plan_analyze_cmd(cd: any, pert: boolean, resources: boolean, continuity: boolean, format: any): void;
export declare function plan_claim_cmd(item_id: string, agent_id: any, cd: any): void;
export declare function plan_complete_cmd(item_id: string, agent_id: any, cd: any): void;
export declare function plan_do_next_cmd(cd: any, limit: number, format: any): void;
export declare function plan_get_next_cmd(cd: any, format: any): void;
export declare function plan_incorporate_cmd(cd: any, dry_run: boolean): void;
export declare function plan_loop_cmd(cd: any, max_iterations: number, sleep_seconds: number, agent: string, dry_run: boolean): void;
export declare function plan_progress_cmd(limit: number, format: any): void;
export declare function plan_wait_next_cmd(cd: any, poll: number, timeout: number, sources: any, format: any): void;
export declare function policy_check_cmd(agent: string, model: any, lane: string, confidence: number): void;
export declare function policy_purge_cmd(dry_run: boolean): void;
export declare function policy_show_cmd(): void;
export declare function project_list_cmd(): void;
export declare function project_register_cmd(path: string, name: any): void;
export declare function prompt_key(msg: string): string;
export declare function ps_cmd(all_sessions: boolean, owner: any, format: any, include_contract: boolean): void;
export declare function purge_cmd(dry_run: boolean): void;
export declare function quality_index_cmd(format: any, no_cache: boolean): void;
export declare function queue_list_cmd(watch: boolean): void;
export declare function recover_status_cmd(): void;
export declare function release_pack_cmd(version: string): void;
export declare function replay_cmd(run_id: string, what_if_env: any): void;
export declare function resolve_model_route_cmd(model: string, provider: any, policy: string, quality_floor: number, lane: any): void;
export declare function resume_cmd(session_id: any): void;
export declare function retry_cmd(run_id: any, agent: any, failover: boolean, cd: any, override_reason: any): void;
export declare function roadmap_cmd(): void;
export declare function rules_sync_cmd(force: boolean, check: boolean, cd: any): void;
export declare function run_cmd(agent: any, prompt: string, cd: any, mode: string, timeout: number, full: boolean, live: boolean, model: any, provider: any, failover: boolean, routing: any, include_contract: boolean, run_id: any, lane: string, idempotency_token: any, confidence: any, arbitration: any, override_reason: any, contract_version: any, domain: any, speculative: boolean, search: boolean, debug: boolean, task_id: any, shadow: boolean, lock: any, remote: any): void;
export declare function run_diff_cmd(run_a: string, run_b: string): void;
export declare function scratchpad_cmd(action: string, content: any): void;
export declare function self_heal_tests_cmd(test_output: any): void;
export declare function session_cmd(session_id: any, watch: boolean, action: any): void;
export declare function session_contract_health_gate_cmd(all_sessions: boolean, owner: any, strict: boolean, format: any, min_healthy_ratio: number, policy_profile: any, no_worse_than_baseline: boolean, regression_tolerance: number, output: any, export_format: any, overwrite: boolean): void;
export declare function session_contract_health_report_cmd(all_sessions: boolean, owner: any, strict: boolean, top_blocked: number, policy_profile: any, no_worse_than_baseline: boolean, regression_tolerance: number, format: any, output: any, export_format: any, overwrite: boolean): void;
export declare function session_contract_health_trend_cmd(payload_type: string, all_sessions: boolean, owner: any, strict: boolean, policy_profile: any, min_healthy_ratio: number, top_blocked: number, limit: number, format: any, output: any, export_format: any, overwrite: boolean): void;
export declare function session_contract_negotiate_cmd(contract_id: string, supported_versions: string, format: any): void;
export declare function session_contract_trend_analysis_cmd(): void;
export declare function session_contracts_cmd(all_sessions: boolean, owner: any, format: any, missing_only: boolean, summary_only: boolean, strict: boolean): void;
export declare function set_env(key: string, value: string): void;
export declare function setup_cmd(api_key: string, model: string, openrouter_key: string, kilo_key: string, zai_key: string, minimax_key: string, wizard: boolean, links: boolean, hooks: boolean, skills: boolean, harness: boolean, full: boolean, agents: string): void;
export declare function signatures_list_cmd(limit: number, format: any): void;
export declare function signatures_verify_cmd(run_id: string): void;
export declare function sitback_dashboard_cmd(refresh: any, format: any, profile: string): void;
export declare function speed_index_cmd(format: any, no_cache: boolean): void;
export declare function status_cmd(session_id: any, format: any, include_contract: boolean): void;
export declare function stop_cmd(session_id: any, force: boolean, wind_down: boolean, grace: number): void;
export declare function summary_cmd(period: string, project: any, summarize: boolean, agent: string, full: boolean, format: any): void;
export declare function sweep_cmd(drift_window: number, include_audit: boolean, format: any): void;
export declare function takeover_cmd(session_id: string): void;
export declare function team_create_cmd(name: string, leader: any, teammates: any): void;
export declare function team_task_add_cmd(team_id: string, title: string, description: string): void;
export declare function team_task_list_cmd(team_id: string): void;
export declare function teammates_delegate_cmd(teammate_id: string, prompt: string, parent_run_id: string): void;
export declare function teammates_list_cmd(): void;
export declare function teammates_status_cmd(run_id: string): void;
export declare function terminal_route_cmd(prompt: string, cd: any): void;
export declare function trace_replay_cmd(run_id: string): void;
export declare function traffic_cmd(): void;
export declare function trust_status_cmd(format: any): void;
export declare function usage_cmd(format: any, include_cost: boolean): void;
export declare function wait_cmd(session_id: any, timeout: number): void;
export declare function watchdog_cmd(max_idle_s: number): void;
export declare function workstream_dashboard_cmd(): void;
export declare function workstream_dependencies_cmd(): void;
export declare function workstream_launch_cmd(): void;
export declare function workstream_query_cmd(query: string): void;
export declare function workstream_stats_cmd(): void;
export declare function wrapper(): void;
