#!/bin/bash
export PYTHONPATH=src
QUERIES=(
    "zsh performance benchmarks 2026"
    "ghostty vs kitty vs alacritty latency"
    "rust cli library comparison"
    "python pydantic v2 performance"
    "mcp protocol implementation agents"
    "autonomous agent framework 2026"
    "terminal emulators gpu acceleration"
    "zsh-autosuggestions performance impact"
    "oh-my-zsh vs prezto vs zim"
    "fastest shell for macos 2026"
    "cli tool design best practices"
    "go lang cli frameworks"
    "distributed agent systems research"
    "mcp vs lsp for ai agents"
    "ghostty configuration examples"
    "performance optimization zsh startup"
    "nushell benchmarks 2026"
    "fish shell vs zsh speed"
    "terminal multiplexers alternatives 2026"
    "ai agent tool calling optimization"
    "python fastmcp tutorial"
    "langchain vs autogen vs crewai 2026"
    "rust async runtime performance"
    "macos process management cli"
    "high performance terminal logging"
    "cli progress bars rust"
    "tui frameworks comparison 2026"
    "opentui react framework"
    "ssh performance optimization"
    "git status slow on large repos"
    "zsh completions optimization"
    "dotfiles management tools 2026"
    "starship prompt performance"
    "eza vs ls vs exa benchmarks"
    "bat vs cat performance"
    "ripgrep vs grep speed"
    "fd vs find benchmarks"
    "fzf vs peco vs selecta"
    "direnv performance overhead"
    "asdf vs rbenv vs nvm"
    "brew bundle vs nix-darwin"
    "macos window managers 2026"
    "aerospace window manager macos"
    "sketchybar configuration"
    "raycast vs alfred vs spotlight"
    "warp terminal vs ghostty"
    "rio terminal benchmarks"
    "foot terminal wayland macos"
    "wezterm vs ghostty latency"
    "iterm2 vs ghostty performance"
    "zsh history expansion guide"
    "bash to zsh migration 2026"
    "cli tools for data science"
    "ai agents for devops"
    "infrastructure as code 2026 tools"
)

INDEX=11
for QUERY in "${QUERIES[@]}"; do
    echo "Running DRP for: $QUERY"
    python3 src/thegent/main.py research deep "$QUERY" --output "drp_results_${INDEX}.json"
    INDEX=$((INDEX + 1))
done
# Additional high-volume queries for 5k expansion
INDEX=65
QUERIES=(
    "awesome-zsh-plugins"
    "awesome-cli-apps"
    "awesome-rust-cli"
    "awesome-python-cli"
    "awesome-macos-cli"
    "awesome-terminal-emulators"
    "awesome-shell-prompts"
    "awesome-zsh-completions"
    "awesome-neovim-plugins"
    "awesome-tmux-config"
    "awesome-git-tools"
    "awesome-docker-cli"
    "awesome-kubernetes-cli"
    "awesome-ai-agents"
    "awesome-mcp-servers"
    "awesome-llm-agents"
    "awesome-langchain"
    "awesome-autogen"
    "awesome-crewai"
    "awesome-agentic-workflow"
    "awesome-performance-optimization"
    "awesome-latency-benchmarks"
    "awesome-rust-performance"
    "awesome-python-performance"
    "awesome-go-performance"
    "awesome-linux-cli"
    "awesome-unix-shell"
    "awesome-bash-scripts"
    "awesome-fish-shell"
    "awesome-nushell"
    "awesome-developer-tools"
    "awesome-workflow-automation"
    "awesome-automation-tools"
    "awesome-ai-research"
    "awesome-academic-search"
    "awesome-arxiv-tools"
    "awesome-papers-with-code"
    "awesome-machine-learning-papers"
    "awesome-deep-learning-papers"
    "awesome-reinforcement-learning"
    "awesome-autonomous-agents"
    "awesome-self-hosted-agents"
    "awesome-open-source-agents"
    "awesome-agent-eval"
    "awesome-cli-ux"
    "awesome-tui-libraries"
    "awesome-command-line-utilities"
    "awesome-productivity-tools"
    "awesome-macos-tweaks"
    "awesome-system-administration"
)

for QUERY in "${QUERIES[@]}"; do
    echo "Running DRP for: $QUERY"
    python3 src/thegent/main.py research deep "$QUERY" --output "drp_results_${INDEX}.json"
    INDEX=$((INDEX + 1))
done
