"""Icon mapping for MCP tool catalog rendering."""

from __future__ import annotations

# G-FM-04: Icon mapping for tools; wire when FastMCP supports icon parameter
# Uses Unicode symbols (not emoji) for consistent terminal rendering
TOOL_ICONS: dict[str, str] = {
    "thegent_run": "▶",
    "thegent_plan_status": "≡",
    "thegent_plan_get": "▤",
    "thegent_plan_save": "⌃",
    "thegent_plan_approve": "✓",
    "thegent_protocol_list": "≡",
    "thegent_protocol_get": "≡",
    "thegent_discussion_finalize": "◉",
    "thegent_research_finalize": "⊕",
    "thegent_validation_report": "✓",
    "thegent_plan_create": "✎",
    "thegent_team_create": "⊕",
    "thegent_team_list": "≡",
    "thegent_team_delegate": "→",
    "thegent_discussion_start": "◉",
    "thegent_discussion_add_question": "?",
    "thegent_bg": "⏸",
    "thegent_stop": "⏹",
    "thegent_pause": "⏸",
    "thegent_resume": "▶",
    "thegent_continuity_snapshot": "≡",
    "thegent_suggest_mode": "◎",
    "thegent_logs": "▤",
    "thegent_ps": "≡",
    "thegent_status": "ℹ",
    "thegent_wait": "⏳",
    "thegent_inbox_list": "↓",
    "thegent_inbox_wait": "⊞",
    "thegent_inspect": "⌕",
    "thegent_list_agents": "⊕",
    "thegent_list_droids": "◉",
    "thegent_list_models": "⊞",
    "thegent_dag_list": "▣",
    "thegent_dag_ready": "▣",
    "thegent_dag_recover": "↺",
    "thegent_dag_run": "▶",
    "thegent_dag_sync": "↻",
    "thegent_observe_summary": "↑",
    "thegent_config_resolve": "◎",
    "thegent_sitback_dashboard": "⊞",
    "thegent_terminal_list": "⊞",
    "thegent_terminal_inspect": "◉",
    "thegent_terminal_send": "⌨",
    "thegent_terminal_attach": "⎘",
    "thegent_ddg_search": "⌕",
    "thegent_do_next": "→",
    "thegent_plan_get_next": "▤",
    "thegent_plan_progress": "≡",
    "thegent_plan_analyze": "⊕",
    "thegent_plan_wait_next": "⏳",
    "thegent_history": "≡",
    "thegent_retry": "↺",
    "thegent_plan_incorporate": "⌃",
    "thegent_dag_status": "▣",
    "thegent_escalate_list": "↑",
    "thegent_escalate_add": "↑",
    "thegent_escalate_approve": "✓",
    "thegent_escalate_resolve": "✓",
    "thegent_handoff": "↔",
    "thegent_handoff_list": "≡",
    "thegent_handoff_show": "◉",
    "thegent_handoff_confirm": "✓",
    "thegent_queue_list": "≡",
    "thegent_queue_claim": "→",
    "thegent_queue_done": "✓",
    "thegent_queue_add": "⊕",
    "thegent_queue_edit": "✎",
    "thegent_queue_release": "↺",
    "thegent_queue_extend_lease": "⏳",
    "thegent_terminal_route": "⌨",
    "thegent_free": "▶",
    "thegent_flash": "⚡",
    "thegent_elicit_confirmation": "?",
    "thegent_elicit_choice": "◎",
    "thegent_elicit_text": "✎",
    "thegent_storage_get": "▤",
    "thegent_storage_set": "⌃",
    "thegent_events_emit": "↑",
    "thegent_events_replay": "≡",
    "thegent_macos_run_script": "⌘",
}

