#!/usr/bin/env zsh
# Package manager coordination wrapper - solves lock contention for uv and npm
# Generated by thegent MTSP-15

# Avoid double-sourcing
[[ -n "${_PKG_WRAPPER_LOADED:-}" ]] && return 0
_PKG_WRAPPER_LOADED=1

# uv accelerator: Handle concurrent uv operations
uv() {
  local cmd="$1"
  [[ -z "$cmd" ]] && { command uv; return $?; }
  shift

  # For read-only or info commands, just run natively
  case "$cmd" in
    help|--version|--help|view|tree|list)
      command uv "$cmd" "$@"
      return $?
      ;;
  esac

  # For write/sync operations, use a mutex
  # uv usually handles its own locking, but in multi-agent environments,
  # we want to provide a cleaner wait/retry loop and telemetry.
  local lock_name
  lock_name=$(printf '%s' "${PROJECT_DIR:-.}" | hash_for_cache)
  local mutex_lock="/tmp/thegent-uv-${lock_name}.lock"
  
  (
    # Use flock for cross-process mutex if available
    exec 8>"$mutex_lock"
    if command -v flock >/dev/null 2>&1; then
      if ! flock -x -w 60 8; then
        echo "UV-MUTEX: Timed out waiting for uv lock. Another agent is likely installing/syncing." >&2
        exit 128
      fi
    else
      # Fallback for macOS/systems without flock: skip explicit lock and rely on uv's internal locking
      # or use a simple directory-based lock if needed.
      :
    fi
    
    command uv "$cmd" "$@"
  )
  return $?
}

# npm accelerator: Handle concurrent npm operations
npm() {
  local cmd="$1"
  [[ -z "$cmd" ]] && { command npm; return $?; }
  shift

  # Only wrap install/ci/update
  case "$cmd" in
    install|i|ci|update|up|uninstall|un)
      local lock_name
      lock_name=$(printf '%s' "${PROJECT_DIR:-.}" | hash_for_cache)
      local mutex_lock="/tmp/thegent-npm-${lock_name}.lock"
      
      (
        exec 9>"$mutex_lock"
        if command -v flock >/dev/null 2>&1; then
          if ! flock -x -w 120 9; then
            echo "NPM-MUTEX: Timed out waiting for npm lock (120s)." >&2
            exit 128
          fi
        fi
        
        command npm "$cmd" "$@"
      )
      return $?
      ;;
    *)
      command npm "$cmd" "$@"
      return $?
      ;;
  esac
}

if [ -n "${BASH_VERSION:-}" ]; then
  export -f uv npm
fi
