"""Icon mapping for MCP tool catalog rendering."""

from __future__ import annotations

# G-FM-04: Icon mapping for tools; wire when FastMCP supports icon parameter
# Uses Unicode symbols (not emoji) for consistent terminal rendering
TOOL_ICONS: dict[str, str] = {
    "phenotype_thegent_run": "▶",
    "phenotype_thegent_plan_status": "≡",
    "phenotype_thegent_plan_get": "▤",
    "phenotype_thegent_plan_save": "⌃",
    "phenotype_thegent_plan_approve": "✓",
    "phenotype_thegent_protocol_list": "≡",
    "phenotype_thegent_protocol_get": "≡",
    "phenotype_thegent_discussion_finalize": "◉",
    "phenotype_thegent_research_finalize": "⊕",
    "phenotype_thegent_validation_report": "✓",
    "phenotype_thegent_plan_create": "✎",
    "phenotype_thegent_team_create": "⊕",
    "phenotype_thegent_team_list": "≡",
    "phenotype_thegent_team_delegate": "→",
    "phenotype_thegent_discussion_start": "◉",
    "phenotype_thegent_discussion_add_question": "?",
    "phenotype_thegent_bg": "⏸",
    "phenotype_thegent_stop": "⏹",
    "phenotype_thegent_pause": "⏸",
    "phenotype_thegent_resume": "▶",
    "phenotype_thegent_continuity_snapshot": "≡",
    "phenotype_thegent_suggest_mode": "◎",
    "phenotype_thegent_logs": "▤",
    "phenotype_thegent_ps": "≡",
    "phenotype_thegent_status": "ℹ",
    "phenotype_thegent_wait": "⏳",
    "phenotype_thegent_inbox_list": "↓",
    "phenotype_thegent_inbox_wait": "⊞",
    "phenotype_thegent_inspect": "⌕",
    "phenotype_thegent_list_agents": "⊕",
    "phenotype_thegent_list_droids": "◉",
    "phenotype_thegent_list_models": "⊞",
    "phenotype_thegent_dag_list": "▣",
    "phenotype_thegent_dag_ready": "▣",
    "phenotype_thegent_dag_recover": "↺",
    "phenotype_thegent_dag_run": "▶",
    "phenotype_thegent_dag_sync": "↻",
    "phenotype_thegent_observe_summary": "↑",
    "phenotype_thegent_config_resolve": "◎",
    "phenotype_thegent_sitback_dashboard": "⊞",
    "phenotype_thegent_terminal_list": "⊞",
    "phenotype_thegent_terminal_inspect": "◉",
    "phenotype_thegent_terminal_send": "⌨",
    "phenotype_thegent_terminal_attach": "⎘",
    "phenotype_thegent_ddg_search": "⌕",
    "phenotype_thegent_do_next": "→",
    "phenotype_thegent_plan_get_next": "▤",
    "phenotype_thegent_plan_progress": "≡",
    "phenotype_thegent_plan_analyze": "⊕",
    "phenotype_thegent_plan_wait_next": "⏳",
    "phenotype_thegent_history": "≡",
    "phenotype_thegent_retry": "↺",
    "phenotype_thegent_plan_incorporate": "⌃",
    "phenotype_thegent_dag_status": "▣",
    "phenotype_thegent_escalate_list": "↑",
    "phenotype_thegent_escalate_add": "↑",
    "phenotype_thegent_escalate_approve": "✓",
    "phenotype_thegent_escalate_resolve": "✓",
    "phenotype_thegent_handoff": "↔",
    "phenotype_thegent_handoff_list": "≡",
    "phenotype_thegent_handoff_show": "◉",
    "phenotype_thegent_handoff_confirm": "✓",
    "phenotype_thegent_queue_list": "≡",
    "phenotype_thegent_queue_claim": "→",
    "phenotype_thegent_queue_done": "✓",
    "phenotype_thegent_queue_add": "⊕",
    "phenotype_thegent_queue_edit": "✎",
    "phenotype_thegent_queue_release": "↺",
    "phenotype_thegent_queue_extend_lease": "⏳",
    "phenotype_thegent_terminal_route": "⌨",
    "phenotype_thegent_free": "▶",
    "phenotype_thegent_flash": "⚡",
    "phenotype_thegent_elicit_confirmation": "?",
    "phenotype_thegent_elicit_choice": "◎",
    "phenotype_thegent_elicit_text": "✎",
    "phenotype_thegent_storage_get": "▤",
    "phenotype_thegent_storage_set": "⌃",
    "phenotype_thegent_events_emit": "↑",
    "phenotype_thegent_events_replay": "≡",
    "phenotype_thegent_macos_run_script": "⌘",
}
