#!/usr/bin/env bash
#===============================================================================
# Codebase Atlas Generator
# Auto-generates visual tree maps on each commit/push
#===============================================================================

set -euo pipefail

# Configuration
ATLAS_DIR="${ATLAS_DIR:-.atlas}"
QUIET_MODE="${ATLAS_QUIET:-false}"
CONFIG_FILE="${ATLAS_DIR}/atlas_config.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

#-------------------------------------------------------------------------------
# Helpers
#-------------------------------------------------------------------------------

log_info() { [[ "$QUIET_MODE" != "true" ]] && echo -e "${BLUE}[INFO]${NC} $*" || true; }
log_success() { [[ "$QUIET_MODE" != "true" ]] && echo -e "${GREEN}[SUCCESS]${NC} $*" || true; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

count_loc() {
    local file="$1"
    [[ -f "$file" ]] && wc -l < "$file" 2>/dev/null | tr -d ' ' || echo 0
}

get_extension() {
    echo "${1##*.}" | tr '[:upper:]' '[:lower:]'
}

map_tech() {
    local ext="$1"
    case "$ext" in
        rs) echo "Rust" ;;
        py) echo "Python" ;;
        js|jsx|mjs|cjs) echo "JavaScript" ;;
        ts|tsx) echo "TypeScript" ;;
        go) echo "Go" ;;
        java) echo "Java" ;;
        kt|kts) echo "Kotlin" ;;
        rb) echo "Ruby" ;;
        cpp|cxx|hpp|h) echo "C++" ;;
        c|h) echo "C" ;;
        cs) echo "C#" ;;
        swift) echo "Swift" ;;
        zig) echo "Zig" ;;
        md|markdown) echo "Markdown" ;;
        yaml|yml) echo "YAML" ;;
        json) echo "JSON" ;;
        toml) echo "TOML" ;;
        sh|bash|zsh|fish) echo "Shell" ;;
        css|scss|sass) echo "CSS" ;;
        html|htm) echo "HTML" ;;
        vue|svelte) echo "Component" ;;
        sql) echo "SQL" ;;
        tf|hcl) echo "Terraform" ;;
        dockerfile) echo "Docker" ;;
        makefile) echo "Make" ;;
        gradle) echo "Gradle" ;;
        xml) echo "XML" ;;
        proto) echo "Protobuf" ;;
        *) echo "Other" ;;
    esac
}

progress_bar() {
    local pct="$1"
    local width="${2:-40}"
    local filled=$((pct * width / 100))
    [[ $filled -gt $width ]] && filled=$width
    printf '%*s' "$filled" | tr ' ' '█'
    printf '%*s' $((width - filled)) | tr ' ' '░'
}

#-------------------------------------------------------------------------------
# Collect File Statistics
#-------------------------------------------------------------------------------

collect_stats() {
    local root_dir="${1:-.}"
    local stats_file="${ATLAS_DIR}/stats_temp.json"

    mkdir -p "$ATLAS_DIR"

    log_info "Collecting file statistics..."

    local total_loc=0
    local total_files=0
    local by_language="{}"
    local files_json="[]"

    # Get tracked files
    while IFS= read -r file; do
        [[ -f "$file" ]] || continue

        # Skip binary files
        [[ "$file" =~ \.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map|bin|so|dylib|a|exe)$ ]] && continue
        [[ "$file" =~ node_modules|vendor|\.git|\.venv|__pycache__|\.next|\.nuxt|target|dist|build|coverage ]] && continue

        local loc
        loc=$(count_loc "$file")
        [[ "$loc" == "0" ]] && continue

        local ext
        ext=$(get_extension "$file")
        local tech
        tech=$(map_tech "$ext")

        total_loc=$((total_loc + loc))
        total_files=$((total_files + 1))

        # Add to files array
        local file_json
        file_json=$(printf '{"file":"%s","loc":%s,"ext":"%s","tech":"%s"}' "$file" "$loc" "$ext" "$tech")
        files_json=$(echo "$files_json" | jq ". + [$file_json]" 2>/dev/null || echo "$files_json")

    done < <(git ls-files 2>/dev/null || find . -type f)

    # Save stats
    local stats_json
    stats_json=$(printf '{
  "total_loc": %d,
  "total_files": %d,
  "total_languages": %d,
  "files": %s,
  "generated_at": "%s",
  "repo_name": "%s"
}' "$total_loc" "$total_files" 0 "$files_json" "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$(basename "$(git remote get-url origin 2>/dev/null || echo ".")" .git 2>/dev/null || echo "local")")

    echo "$stats_json" > "$stats_file"
    echo "$stats_file"
}

#-------------------------------------------------------------------------------
# Generate File Tree
#-------------------------------------------------------------------------------

generate_file_tree() {
    local stats_file="$1"
    local output="${ATLAS_DIR}/file_tree.md"
    local total_loc
    total_loc=$(jq -r '.total_loc' "$stats_file")
    local total_files
    total_files=$(jq -r '.total_files' "$stats_file")

    cat > "$output" << 'HEADER'
# File Tree Atlas

Generated by `generate_codebase_atlas.sh`

## Files by LOC

```
HEADER

    jq -r '.files | sort_by(-.loc) | .[] | "| \(.file) | \(.loc) |"' "$stats_file" 2>/dev/null | \
        while IFS='|' read -r file loc; do
            [[ -z "$loc" ]] && continue
            local pct
            pct=$(echo "scale=1; $loc * 100 / $total_loc" | bc 2>/dev/null || echo "0")
            local bar
            bar=$(progress_bar "${pct%.*}" 30)
            printf '%s  %-40s %6s LOC %s%%\n' "$bar" "$file" "$loc" "$pct"
        done >> "$output"

    cat >> "$output" << FOOTER
```

**Total:** $total_loc LOC across $total_files files

FOOTER

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Generate Folder Tree
#-------------------------------------------------------------------------------

generate_folder_tree() {
    local stats_file="$1"
    local output="${ATLAS_DIR}/folder_tree.md"
    local total_loc
    total_loc=$(jq -r '.total_loc' "$stats_file")

    cat > "$output" << 'HEADER'
# Folder Tree Atlas

Generated by `generate_codebase_atlas.sh`

## Directory Hierarchy by LOC

```
HEADER

    # Group by directory
    jq -r '.files | group_by(.file | split("/") | .[0:-1] | join("/")) |
        map({path: (.[0].file | split("/") | .[0:-1] | join("/") // "./"), loc: (map(.loc) | add)}) |
        sort_by(-.loc) |
        .[0:30][] |
        .path + "|" + (.loc | tostring)' "$stats_file" 2>/dev/null | \
        while IFS='|' read -r path loc; do
            [[ -z "$loc" ]] && continue
            local pct
            pct=$(echo "scale=1; $loc * 100 / $total_loc" | bc 2>/dev/null || echo "0")
            local bar
            bar=$(progress_bar "${pct%.*}" 30)
            printf '%s  %-30s %6s LOC %s%%\n' "$bar" "$path" "$loc" "$pct"
        done >> "$output"

    cat >> "$output" << 'FOOTER'
```

**Legend:** █ = LOC proportion

FOOTER

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Generate Tech Tree
#-------------------------------------------------------------------------------

generate_tech_tree() {
    local stats_file="$1"
    local output="${ATLAS_DIR}/tech_tree.md"
    local total_loc
    total_loc=$(jq -r '.total_loc' "$stats_file")

    cat > "$output" << 'HEADER'
# Technology Tree Atlas

Generated by `generate_codebase_atlas.sh`

## Code Distribution by Language

```mermaid
pie showData title Code by Language
HEADER

    jq -r '.files | group_by(.tech) |
        map({tech: .[0].tech, loc: (map(.loc) | add)}) |
        sort_by(-.loc) |
        .[] |
        "    \"\(.tech) (\(.loc))\" : \(.loc)"' "$stats_file" >> "$output"

    cat >> "$output" << 'MIDDLE'
```

## Detailed Breakdown

| Language | Files | LOC | Distribution |
|----------|-------|-----|--------------|
MIDDLE

    jq -r '.files | group_by(.tech) |
        map({tech: .[0].tech, files: length, loc: (map(.loc) | add)}) |
        sort_by(-.loc) |
        .[] |
        "| \(.tech) | \(.files) | \(.loc) |" |
        progress_bar ((.loc * 40 / '"$total_loc"')) + " |"' "$stats_file" >> "$output"

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Generate Feature Tree
#-------------------------------------------------------------------------------

generate_feature_tree() {
    local stats_file="$1"
    local output="${ATLAS_DIR}/feature_tree.md"

    cat > "$output" << 'HEADER'
# Feature Tree Atlas

Generated by `generate_codebase_atlas.sh`

Inferred feature groupings based on directory structure.

## Feature Modules

```mermaid
graph TD
    subgraph "Features"
HEADER

    jq -r '.files | [.[] | .file | split("/") | .[0]] | unique | .[] |
        "        F_\(. | gsub("[^a-zA-Z0-9]";"_"))[\"\(.)\"]"' "$stats_file" 2>/dev/null >> "$output"

    cat >> "$output" << 'MIDDLE'
    end
```

## Feature Breakdown

| Feature | Files | LOC | Top Files |
|---------|-------|-----|-----------|
MIDDLE

    jq -r '.files |
        group_by(.file | split("/") | .[0]) |
        map({feat: .[0].file | split("/") | .[0], files: length, loc: (map(.loc) | add), top: (map({file, loc}) | sort_by(-.loc) | .[0:2] | map(.file | split("/") | .[-1]))}) |
        sort_by(-.loc) |
        .[0:20][] |
        "| \(.feat) | \(.files) | \(.loc) | \(.top | join(", ")) |"' "$stats_file" >> "$output"

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Generate User Tree
#-------------------------------------------------------------------------------

generate_user_tree() {
    local output="${ATLAS_DIR}/user_tree.md"

    cat > "$output" << 'HEADER'
# User Tree Atlas

Generated by `generate_codebase_atlas.sh`

## Code Ownership (LOC by Contributor)

```mermaid
pie showData title Code Ownership
HEADER

    git blame --line-porcelain . 2>/dev/null | \
        grep '^author ' | \
        sed 's/^author //' | \
        sort | \
        uniq -c | \
        sort -rn | \
        head -15 | \
        while read count author; do
            printf '    \"%s\" : %d\n' "$author" "$count"
        done >> "$output"

    cat >> "$output" << 'MIDDLE'
```

## Contributor Breakdown

| Contributor | Lines | Percentage |
|-------------|-------|------------|
MIDDLE

    git blame --line-porcelain . 2>/dev/null | \
        grep '^author ' | \
        sed 's/^author //' | \
        sort | \
        uniq -c | \
        sort -rn | \
        head -15 | \
        while read count author; do
            local total
            total=$(git rev-list --all --count 2>/dev/null || echo 1)
            local pct
            pct=$(echo "scale=1; $count * 100 / $total" | bc 2>/dev/null || echo "0")
            printf '| %s | %d | %s%% |\n' "$author" "$count" "$pct"
        done >> "$output"

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Generate Index
#-------------------------------------------------------------------------------

generate_index() {
    local stats_file="$1"
    local output="${ATLAS_DIR}/README.md"
    local total_loc
    total_loc=$(jq -r '.total_loc' "$stats_file")
    local total_files
    total_files=$(jq -r '.total_files' "$stats_file")
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local repo_name
    repo_name=$(jq -r '.repo_name' "$stats_file")
    local num_languages
    num_languages=$(jq '[.files[].tech] | unique | length' "$stats_file" 2>/dev/null || echo "N/A")
    local largest_file
    largest_file=$(jq -r '.files | sort_by(-.loc) | .[0] | "\(.file) (\(.loc) LOC)"' "$stats_file" 2>/dev/null || echo "N/A")

    cat > "$output" << HEADER
# Codebase Atlas

**Repository:** $repo_name
**Generated:** $timestamp
**Total LOC:** $total_loc
**Total Files:** $total_files

## Atlas Views

| View | Description | File |
|------|-------------|------|
| [File Tree](./file_tree.md) | All files sorted by LOC | file_tree.md |
| [Folder Tree](./folder_tree.md) | Directory hierarchy with LOC | folder_tree.md |
| [Technology Tree](./tech_tree.md) | Code by programming language | tech_tree.md |
| [Feature Tree](./feature_tree.md) | Inferred feature modules | feature_tree.md |
| [User Tree](./user_tree.md) | Code ownership by contributor | user_tree.md |

## Quick Stats

- **Languages:** $num_languages
- **Largest File:** $largest_file

## Mermaid Overview

\`\`\`mermaid
graph TD
    subgraph "Codebase Atlas"
        A[Root] --> B[src/]
        A --> C[tests/]
        A --> D[docs/]
    end
\`\`\`
HEADER

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Generate JSON Stats
#-------------------------------------------------------------------------------

generate_stats_json() {
    local stats_file="$1"
    local output="${ATLAS_DIR}/stats.json"

    # Calculate language stats
    jq '{
        total_loc: .total_loc,
        total_files: .total_files,
        total_languages: (.files | group_by(.tech) | length),
        files: (.files | sort_by(-.loc) | .[0:100]),
        by_language: (.files | group_by(.tech) | map({key: .[0].tech, value: {loc: (map(.loc) | add), files: length}}) | from_entries),
        by_folder: (.files | group_by(.file | split("/") | .[0]) | map({key: .[0].file | split("/") | .[0], value: {loc: (map(.loc) | add), files: length}}) | from_entries),
        generated_at: .generated_at,
        repo_name: .repo_name
    }' "$stats_file" > "$output"

    log_success "Generated: $output"
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

main() {
    local repo_root
    repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
    cd "$repo_root"

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --quiet|-q)
                QUIET_MODE="true"
                ;;
            --output-dir|-o)
                ATLAS_DIR="$2"
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [--quiet] [--output-dir DIR]"
                exit 0
                ;;
        esac
        shift
    done

    log_info "Generating codebase atlas for: $(basename "$repo_root")"

    mkdir -p "$ATLAS_DIR"

    local stats_file
    stats_file=$(collect_stats "$repo_root")

    generate_file_tree "$stats_file"
    generate_folder_tree "$stats_file"
    generate_tech_tree "$stats_file"
    generate_feature_tree "$stats_file"
    generate_user_tree
    generate_index "$stats_file"
    generate_stats_json "$stats_file"

    rm -f "$stats_file"

    log_success "Atlas generation complete!"
    [[ "$QUIET_MODE" != "true" ]] && ls -la "$ATLAS_DIR"/*.md
}

main "$@"
