#!/usr/bin/env python3
"""Fail on new mypy errors relative to a checked-in baseline."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ERROR_RE = re.compile(r"^(?P<path>[^:\n]+):(?P<line>\d+): error: (?P<msg>.+?)\s+\[(?P<code>[^\]]+)\]\s*$")
FOUND_RE = re.compile(r"^Found \d+ errors? in \d+ files?.*$")


def _canon(path: str, msg: str, code: str) -> str:
    return f"{path}::{code}::{msg}"


def parse_errors(text: str) -> tuple[set[str], dict[str, str]]:
    errors: set[str] = set()
    samples: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        m = ERROR_RE.match(line)
        if m:
            key = _canon(m.group("path"), m.group("msg"), m.group("code"))
            errors.add(key)
            samples.setdefault(
                key,
                f"{m.group('path')}:{m.group('line')}: error: {m.group('msg')}  [{m.group('code')}]",
            )
    return errors, samples


def filter_baseline_lines(text: str) -> set[str]:
    rows: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or FOUND_RE.match(line):
            continue
        m = ERROR_RE.match(line)
        if m:
            rows.add(_canon(m.group("path"), m.group("msg"), m.group("code")))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--current-log", required=True, type=Path)
    parser.add_argument("--baseline", required=True, type=Path)
    parser.add_argument("--write-baseline", action="store_true")
    args = parser.parse_args()

    if not args.current_log.exists():
        raise SystemExit(f"Current mypy log not found: {args.current_log}")

    current_text = args.current_log.read_text(encoding="utf-8")
    current_errors, sample_by_key = parse_errors(current_text)

    if args.write_baseline:
        args.baseline.parent.mkdir(parents=True, exist_ok=True)
        lines = sorted(sample_by_key[key] for key in current_errors)
        payload = (
            "# mypy non-regression baseline\n"
            "# Auto-generated by scripts/mypy_nonregression_gate.py --write-baseline\n"
            + ("\n".join(lines) + "\n" if lines else "")
        )
        args.baseline.write_text(payload, encoding="utf-8")
        print(f"Wrote baseline: {args.baseline} ({len(lines)} entries)")
        return 0

    if not args.baseline.exists():
        print(f"Missing baseline file: {args.baseline}")
        print("Create it with: task lint:mypy-baseline:update")
        return 2

    baseline_text = args.baseline.read_text(encoding="utf-8")
    baseline_errors = filter_baseline_lines(baseline_text)

    new_errors = sorted(current_errors - baseline_errors)
    fixed_errors = sorted(baseline_errors - current_errors)

    if new_errors:
        print(f"mypy non-regression gate failed: {len(new_errors)} new errors")
        for row in new_errors[:200]:
            print(sample_by_key.get(row, row))
        if len(new_errors) > 200:
            print(f"... truncated ({len(new_errors) - 200} more)")
        return 1

    print(
        "mypy non-regression gate passed: "
        f"new=0 baseline={len(baseline_errors)} current={len(current_errors)} fixed={len(fixed_errors)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
