#!/usr/bin/env bash
# Session-end hook: write conversation dump to docs/research/
# Called on SessionEnd to ensure research/decisions are always persisted.
#
# @trace FR-DX-010

set -euo pipefail

DUMP_DIR="docs/research"
DATE="$(date +%Y-%m-%d)"
DUMP_FILE="${DUMP_DIR}/CONVERSATION_DUMP_${DATE}.md"

# Ensure target directory exists
mkdir -p "${DUMP_DIR}"

# Only append if the file does not already exist for today
if [ ! -f "${DUMP_FILE}" ]; then
    cat > "${DUMP_FILE}" <<EOF
# Conversation Dump ${DATE}

> Auto-generated by session-end-write-dump hook.

## Issues Addressed

- (none recorded)

## Fixes Applied

- (none recorded)

## Research Findings

- (none recorded)

## Open Questions

- (none recorded)

## Next Steps

- (none recorded)
EOF
    echo "[session-end-write-dump] Created ${DUMP_FILE}"
else
    echo "[session-end-write-dump] ${DUMP_FILE} already exists, skipping."
fi
