#!/bin/bash
export PYTHONPATH=src
INDEX=100
QUERIES=(
    "awesome-zsh-plugins"
    "awesome-cli-apps"
    "awesome-rust-cli"
    "awesome-python-cli"
    "awesome-macos-cli"
    "awesome-terminal-emulators"
    "awesome-shell-prompts"
    "awesome-zsh-completions"
    "awesome-neovim-plugins"
    "awesome-tmux-config"
    "awesome-git-tools"
    "awesome-docker-cli"
    "awesome-kubernetes-cli"
    "awesome-ai-agents"
    "awesome-mcp-servers"
    "awesome-llm-agents"
    "awesome-langchain"
    "awesome-autogen"
    "awesome-crewai"
    "awesome-agentic-workflow"
    "awesome-performance-optimization"
    "awesome-latency-benchmarks"
    "awesome-rust-performance"
    "awesome-python-performance"
    "awesome-go-performance"
    "awesome-linux-cli"
    "awesome-unix-shell"
    "awesome-bash-scripts"
    "awesome-fish-shell"
    "awesome-nushell"
    "awesome-developer-tools"
    "awesome-workflow-automation"
    "awesome-automation-tools"
    "awesome-ai-research"
    "awesome-academic-search"
    "awesome-arxiv-tools"
    "awesome-papers-with-code"
    "awesome-machine-learning-papers"
    "awesome-deep-learning-papers"
    "awesome-reinforcement-learning"
    "awesome-autonomous-agents"
    "awesome-self-hosted-agents"
    "awesome-open-source-agents"
    "awesome-agent-eval"
    "awesome-cli-ux"
    "awesome-tui-libraries"
    "awesome-command-line-utilities"
    "awesome-productivity-tools"
    "awesome-macos-tweaks"
    "awesome-system-administration"
)

for QUERY in "${QUERIES[@]}"; do
    echo "Running DRP for: $QUERY"
    python3 src/thegent/main.py research deep "$QUERY" --output "drp_results_${INDEX}.json"
    INDEX=$((INDEX + 1))
done
