name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    uses: phenotype-dev/.github/workflows/rust-ci.yml@main
    with:
      rust-version: '1.75'
