permissions:
  contents: read

name: License Compliance
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  push:
    paths:
      - 'Cargo.toml'
      - 'go.mod'
      - 'package.json'
  schedule:
    - cron: '0 0 * * *'

jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Run cargo-deny
        run: cargo deny check
        continue-on-error: true

  fossa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install FOSSA
        run: |
          curl -sSfL https://github.com/fossas/fossa-cli/releases/download/v3.17.8/fossa_3.17.8_linux_amd64.tar.gz -o fossa.tar.gz && tar xzf fossa.tar.gz && mv fossa /usr/local/bin/fossa && chmod +x /usr/local/bin/fossa
      - name: Run FOSSA
        run: fossa scan repository
        continue-on-error: true