name: Security Guard

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ggshield-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install ggshield
        run: pip install ggshield
      - name: Run ggshield secret scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield secret scan path . --recursive
