name: Security Guard
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Run Trivy
        uses: aquasecurity/trivy-action@314ff8b43182423b84c50b1670b0e10f858f2d98
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
