permissions:
  contents: read

name: Security Guard
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  trivy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run Trivy
        uses: aquasecurity/trivy-action@bfa4b33a029b9aa80ddb784b45574c30e072c59e
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
